//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serial_Comm_Tester.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Serial_Comm_Tester.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ASCII control characters
        ///
        ///
        ///Dec 	Hex 	Binary      Character   Description
        ///	                                
        ///0 	00 	00000000 	NUL 	null
        ///1 	01 	00000001 	SOH 	start of header
        ///2 	02 	00000010 	STX 	start of text
        ///3 	03 	00000011 	ETX 	end of text
        ///4 	04 	00000100 	EOT 	end of transmission
        ///5 	05 	00000101 	ENQ 	enquiry
        ///6 	06 	00000110 	ACK 	acknowledge
        ///7 	07 	00000111 	BEL 	bell
        ///8 	08 	00001000 	BS 	backspace
        ///9 	09 	00001001 	HT 	horizontal tab
        ///10 	0A 	00001010 	LF 	line feed
        ///11 	0B 	00001011 	VT 	 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HEX_to_ASCII {
            get {
                return ResourceManager.GetString("HEX_to_ASCII", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 THIS IS ONLY SOME UNICODE CHARACTERS AS EXAMPLE:
        ///
        ///Symbols codes
        ///&amp; • ◦ ∙ ‣ ⁃ ° ∞
        ///
        ///Currency codes
        /// $ ₨ ₱ ₩ ฿ ₫ ₪
        ///
        ///Intellectual property codes
        ///© ® ℗ ™ ℠
        ///
        ///Greek alphabet codes
        ///α β γ δ ε ζ η θ ι κ λ μ ν ξ ο π ρ σ τ υ φ χ ψ ω Α Β Γ Δ Ε Ζ Η Θ Ι Κ Λ Μ Ν Ξ Ο Π Ρ Σ Τ Υ Φ Χ Ψ Ω
        ///
        ///
        ///
        /// 	! 	&quot; 	# 	$ 	% 	&amp; 	&apos; 	( 	) 	* 	+ 	, 	- 	. 	/
        ///0 	1 	2 	3 	4 	5 	6 	7 	8 	9 	: 	; 	&lt; 	= 	&gt; 	?
        ///@ 	A 	B 	C 	D 	E 	F 	G 	H 	I 	J 	K 	L 	M 	N 	O
        ///P 	Q 	R 	S 	T 	U 	V 	W 	X 	Y 	Z 	[ 	\ 	] 	^ 	_
        ///` 	a 	b 	c 	d 	e 	f 	g 	h 	i 	j 	k [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Unicode_characters {
            get {
                return ResourceManager.GetString("Unicode_characters", resourceCulture);
            }
        }
    }
}
